import "@styles/globals.css";
import Nav from "@components/Nav";
import Provider from "@components/Provider";

export const metadata = {
  title: "Sample Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <Provider>
            <main>
              <Nav />
              {children}
            </main>
          </Provider>   
      </body>
    </html>
  );
}

